import React from 'react';
import image1 from '../images/ecos.png';
import image2 from '../images/paradox.png';



const books = [
  {
    title: "Science Fiction",
    description: "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back...",
    imageUrl: "./images/paradox.png",
    link: "#"
  },
  {
    title: "Mystery",
    description: "The old lighthouse stood silent, its beacon long extinguished...",
    imageUrl: {image1},
    link: "#"
  },
  {
    title: "Fantasy",
    description: "The ancient prophecy spoke of a child born with starlight in their eyes...",
    imageUrl: {image1},
    link: "#"
  },
];

const SampleBooksSection = () => {
  return (
    <section className="py-20 bg-gray-100 dark:bg-gray-900 dark:text-white">
      <div className="max-w-7xl mx-auto px-4 text-center">
        <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-12">Sample Books Generated by BookAI</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {books.map((book, index) => (
            <div key={index} className="p-6 bg-white dark:bg-gray-800 rounded-lg shadow-lg">
              <img src={image2} alt={book.title} className="w-full h-64 object-cover rounded-t-lg mb-4" />
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">{book.title}</h3>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                {book.description}
              </p>
              <a href={book.link} className="text-blue-500 dark:text-blue-400 hover:underline">
                Read More
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default SampleBooksSection;
